### ISSUE TITLE
cannot find ttmux:1

### ISSUE THREAD

**Issue by jlebleu** [sensorario/startmux#34]
Seems that the first tmux windows has to be windows 0, suggest to change from start=1 to start=0 in line 94

**Comment by sensorario** [comment]
I work with this configuration: 

``` bash
# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
```

I need to do some things:
- [ ] check if tmux.conf file is present
- [ ] check if variable is configured in tmux.conf file
- [ ] eventually start from 0 instead of 1

the fact is that starting from 1, for me is better. What do you think about @jlebleu ?

**Comment by jlebleu** [comment]
Ok I didn't know this config tricks :) so sorry for the noise, anyway it would be good to update the readme file with this config.
Thank you for the script was very help full, so I close the issue.

**Comment by sensorario** [comment]
Thank you for the star ^_^. Anyway, ... any suggestion is more than welcomed!
