### ISSUE TITLE
Json/TOML/Ini configuration file

### ISSUE THREAD

**Issue by fntlnz** [sensorario/startmux#6]
To me would make more sense if the config.startmux configuration file was only a configuration file and not an actual piece of bash code used to create an array.

I googled about "ini to bash array"  and found this Unix StackExchange question http://unix.stackexchange.com/questions/149702/how-do-i-add-an-associative-array-to-a-variable-from-an-external-ini-file

Any thoughts?

**Comment by sensorario** [comment]
:+1:

ini files are more readable than associative arrays.

**Comment by sensorario** [comment]
For now, I decided to close this issue.
